name: Test & Deploy
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic
      - name: Run tests
        run: python manage.py test
    env:
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost
      DEVELOPMENT_MODE: "True"
  docker-push:
    name: Push Docker
    runs-on: ubuntu-latest
    needs:
      - Test
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/django-sample:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: docker-push
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "django-sample-kantan"
          heroku_email: "af.decastro879@gmail.com"
          usedocker: true
          docker_build_args: |
            DJANGO_ALLOWED_HOSTS
        env:
          DJANGO_ALLOWED_HOSTS: "django-sample-kantan.herokuapp.com"
